config/routes.rb
Rhadmin::Application.routes.draw do
  resources :departamentos

  resources :cargos

  resources :colaboradors

end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
  attr_accessible :descricao, :nome
end

app/models/colaborador.rb
class Colaborador < ActiveRecord::Base
  attr_accessible :cpf, :nome
end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
  attr_accessible :descricao, :nome, :departamento_funcionarios_attributes
  has_many :departamento_funcionarios, inverse_of: :departamento
  accepts_nested_attributes_for :departamento_funcionarios
end

app/models/departamento_funcionario.rb
class DepartamentoFuncionario < ActiveRecord::Base
  belongs_to :colaborador
  belongs_to :cargo
  belongs_to :departamento
  attr_accessible :colaborador_id, :cargo_id, :departamento_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  # GET /cargos
  # GET /cargos.json
  def index
    @cargos = Cargo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cargos }
    end
  end

  # GET /cargos/1
  # GET /cargos/1.json
  def show
    @cargo = Cargo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cargo }
    end
  end

  # GET /cargos/new
  # GET /cargos/new.json
  def new
    @cargo = Cargo.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cargo }
    end
  end

  # GET /cargos/1/edit
  def edit
    @cargo = Cargo.find(params[:id])
  end

  # POST /cargos
  # POST /cargos.json
  def create
    @cargo = Cargo.new(params[:cargo])

    respond_to do |format|
      if @cargo.save
        format.html { redirect_to @cargo, notice: 'Cargo was successfully created.' }
        format.json { render json: @cargo, status: :created, location: @cargo }
      else
        format.html { render action: "new" }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cargos/1
  # PUT /cargos/1.json
  def update
    @cargo = Cargo.find(params[:id])

    respond_to do |format|
      if @cargo.update_attributes(params[:cargo])
        format.html { redirect_to @cargo, notice: 'Cargo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cargos/1
  # DELETE /cargos/1.json
  def destroy
    @cargo = Cargo.find(params[:id])
    @cargo.destroy

    respond_to do |format|
      format.html { redirect_to cargos_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/colaboradors_controller.rb
class ColaboradorsController < ApplicationController
  # GET /colaboradors
  # GET /colaboradors.json
  def index
    @colaboradors = Colaborador.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @colaboradors }
    end
  end

  # GET /colaboradors/1
  # GET /colaboradors/1.json
  def show
    @colaborador = Colaborador.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @colaborador }
    end
  end

  # GET /colaboradors/new
  # GET /colaboradors/new.json
  def new
    @colaborador = Colaborador.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @colaborador }
    end
  end

  # GET /colaboradors/1/edit
  def edit
    @colaborador = Colaborador.find(params[:id])
  end

  # POST /colaboradors
  # POST /colaboradors.json
  def create
    @colaborador = Colaborador.new(params[:colaborador])

    respond_to do |format|
      if @colaborador.save
        format.html { redirect_to @colaborador, notice: 'Colaborador was successfully created.' }
        format.json { render json: @colaborador, status: :created, location: @colaborador }
      else
        format.html { render action: "new" }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /colaboradors/1
  # PUT /colaboradors/1.json
  def update
    @colaborador = Colaborador.find(params[:id])

    respond_to do |format|
      if @colaborador.update_attributes(params[:colaborador])
        format.html { redirect_to @colaborador, notice: 'Colaborador was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @colaborador.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /colaboradors/1
  # DELETE /colaboradors/1.json
  def destroy
    @colaborador = Colaborador.find(params[:id])
    @colaborador.destroy

    respond_to do |format|
      format.html { redirect_to colaboradors_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamentos = Departamento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @departamentos }
    end
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
    @departamento = Departamento.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @departamento }
    end
  end

  # GET /departamentos/new
  # GET /departamentos/new.json
  def new
    @departamento = Departamento.new
    # @departamento.departamento_funcionarios.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @departamento }
    end
  end

  # GET /departamentos/1/edit
  def edit
    @departamento = Departamento.find(params[:id])
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(params[:departamento])

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to @departamento, notice: 'Departamento was successfully created.' }
        format.json { render json: @departamento, status: :created, location: @departamento }
      else
        format.html { render action: "new" }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /departamentos/1
  # PUT /departamentos/1.json
  def update
    @departamento = Departamento.find(params[:id])

    respond_to do |format|
      if @departamento.update_attributes(params[:departamento])
        format.html { redirect_to @departamento, notice: 'Departamento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento = Departamento.find(params[:id])
    @departamento.destroy

    respond_to do |format|
      format.html { redirect_to departamentos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/helpers/colaboradors_helper.rb
module ColaboradorsHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/views/cargos/_form.html.erb
<%= form_for(@cargo) do |f| %>
  <% if @cargo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cargo.errors.count, "error") %> prohibited this cargo from being saved:</h2>

      <ul>
      <% @cargo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cargos/edit.html.erb
<h1>Editing cargo</h1>

<%= render 'form' %>

<%= link_to 'Show', @cargo %> |
<%= link_to 'Back', cargos_path %>

app/views/cargos/index.html.erb
<h1>Listing cargos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Descricao</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cargos.each do |cargo| %>
  <tr>
    <td><%= cargo.nome %></td>
    <td><%= cargo.descricao %></td>
    <td><%= link_to 'Show', cargo %></td>
    <td><%= link_to 'Edit', edit_cargo_path(cargo) %></td>
    <td><%= link_to 'Destroy', cargo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cargo', new_cargo_path %>

app/views/cargos/new.html.erb
<h1>New cargo</h1>

<%= render 'form' %>

<%= link_to 'Back', cargos_path %>

app/views/cargos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @cargo.nome %>
</p>

<p>
  <b>Descricao:</b>
  <%= @cargo.descricao %>
</p>


<%= link_to 'Edit', edit_cargo_path(@cargo) %> |
<%= link_to 'Back', cargos_path %>

app/views/colaboradors/_form.html.erb
<%= form_for(@colaborador) do |f| %>
  <% if @colaborador.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@colaborador.errors.count, "error") %> prohibited this colaborador from being saved:</h2>

      <ul>
      <% @colaborador.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :cpf %><br />
    <%= f.text_field :cpf %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/colaboradors/edit.html.erb
<h1>Editing colaborador</h1>

<%= render 'form' %>

<%= link_to 'Show', @colaborador %> |
<%= link_to 'Back', colaboradors_path %>

app/views/colaboradors/index.html.erb
<h1>Listing colaboradors</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Cpf</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @colaboradors.each do |colaborador| %>
  <tr>
    <td><%= colaborador.nome %></td>
    <td><%= colaborador.cpf %></td>
    <td><%= link_to 'Show', colaborador %></td>
    <td><%= link_to 'Edit', edit_colaborador_path(colaborador) %></td>
    <td><%= link_to 'Destroy', colaborador, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Colaborador', new_colaborador_path %>

app/views/colaboradors/new.html.erb
<h1>New colaborador</h1>

<%= render 'form' %>

<%= link_to 'Back', colaboradors_path %>

app/views/colaboradors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @colaborador.nome %>
</p>

<p>
  <b>Cpf:</b>
  <%= @colaborador.cpf %>
</p>


<%= link_to 'Edit', edit_colaborador_path(@colaborador) %> |
<%= link_to 'Back', colaboradors_path %>

app/views/departamentos/_departamento_funcionarios.html.erb
<tr>
         <td><%= f.select :colaborador_id, Colaborador.all.map { |c| [c.id, c.nome] }, include_blank: true %></td>
         <td><%= f.select :cargo_id, Cargo.all.map { |c| [c.id, c.nome] }, include_blank: true %></td>
      </tr>

app/views/departamentos/_form.html.erb
<%= nested_form_for(@departamento) do |f| %>
  <% if @departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
      <% @departamento.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :descricao %><br />
    <%= f.text_area :descricao %>
  </div>
  <div class="field">
    <%= f.fields_for :departamento_funcionarios do |builder| %>
       <%= render 'departamento_funcionarios', :f => builder %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing departamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

app/views/departamentos/index.html.erb
<h1>Listing departamentos</h1>

<table>
  <tr>
    <th>Nome</th>
    <th>Descricao</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @departamentos.each do |departamento| %>
  <tr>
    <td><%= departamento.nome %></td>
    <td><%= departamento.descricao %></td>
    <td><%= link_to 'Show', departamento %></td>
    <td><%= link_to 'Edit', edit_departamento_path(departamento) %></td>
    <td><%= link_to 'Destroy', departamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Departamento', new_departamento_path %>

app/views/departamentos/new.html.erb
<h1>New departamento</h1>

<%= render 'form' %>

<%= link_to 'Back', departamentos_path %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome:</b>
  <%= @departamento.nome %>
</p>

<p>
  <b>Descricao:</b>
  <%= @departamento.descricao %>
</p>


<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rhadmin</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>